/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package annotations;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    Person person = new Person("ivan", "sanchez", "29", "Cerezo H8 Zapopan Jalisco");
    ObjectToJsonSerializer serializer = new ObjectToJsonSerializer();
    String personJson = serializer.convertToJson(person);
    System.out.println(personJson);
  }
}
